Import modułów i pakietów

In [1]:
import numpy as np
from keras import Sequential
from keras.layers import Dense
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
from sklearn.preprocessing import OneHotEncoder, LabelEncoder

Wczytywanie danych z pliku csv

In [3]:
data = pd.read_csv('data/all_textures.csv')
X = data.iloc[:, :-1].values
y = data.iloc[:, -1].values

Wstępne przetwarzanie danych

In [4]:
label_encoder = LabelEncoder()
y_int = label_encoder.fit_transform(y)
onehot_encoder = OneHotEncoder(sparse_output=False)
y_onehot = onehot_encoder.fit_transform(y_int.reshape(-1, 1))
X_train, X_test, y_train, y_test = train_test_split(X, y_onehot, test_size=0.3)

Tworzenie modelu sieci neuronowej

In [5]:
model = Sequential()
model.add(Dense(10, activation='sigmoid', input_dim=72))
model.add(Dense(4, activation='softmax'))
model.compile(loss='categorical_crossentropy', optimizer='sgd', metrics=['accuracy'])
model.fit(X_train, y_train, epochs=100, batch_size=10, shuffle=True)

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


Epoch 1/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 2s 130ms/step - accuracy: 0.4947 - loss: 1.4329
Epoch 2/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.3143 - loss: 1.4529 
Epoch 3/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.3414 - loss: 1.2304 
Epoch 4/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.5111 - loss: 1.1197 
Epoch 5/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.4016 - loss: 1.1835 
Epoch 6/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.4438 - loss: 1.0788 
Epoch 7/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.4058 - loss: 1.1483 
Epoch 8/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.5122 - loss: 1.1653 
Epoch 9/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.4105 - loss: 1.1321 
Epoch 10/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.5956 - loss: 0.9835 
Epoch 11/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7231 - loss: 1.0326 
Epoch 12/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6787 - lo

Testowanie sieci

In [6]:
y_pred = model.predict(X_test)
y_test_int = np.argmax(y_test, axis=1)
y_pred_int = np.argmax(y_pred, axis=1)

confusion_mat = confusion_matrix(y_test_int, y_pred_int)
print("Confusion Matrix:")
print(confusion_mat)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 241ms/step
Confusion Matrix:
[[5 0 0 0]
 [0 3 0 0]
 [0 0 7 0]
 [0 0 0 5]]
